services:
  feeddock:
    image: ghcr.io/planeteditorx/feeddock:latest
    container_name: feeddock
    restart: unless-stopped
    pull_policy: always
    ports:
      - "7789:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: "Asia/Shanghai"
      PUID: "1000"
      PGID: "1000"
      UMASK: "022"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "password"
      SESSION_DAYS: "7"
      COOKIE_SECURE: "false"
      POLL_INTERVAL_MINUTES: "10"
      REQUEST_TIMEOUT_SECONDS: "20"

      # 先不配置 qBittorrent
      QBIT_URL: ""
      QBIT_USERNAME: ""
      QBIT_PASSWORD: ""
      QBIT_CATEGORY: "rss"
      DOWNLOAD_PATH: "/downloads/rss"

      UPDATE_REPOSITORY: "planeteditorx/feeddock"
      UPDATE_API_URL: "https://api.github.com"

      # 暂时关闭网页一键更新
      WATCHTOWER_URL: ""
      WATCHTOWER_TOKEN: ""

    volumes:
      - "/vol1/1000/应用/feeddock/data:/data"
