from __future__ import annotations

import socket
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from app.network_diagnostics import (
    NetworkTarget,
    diagnose_dns,
    resolve_host,
    resolver_configuration,
)


class NetworkDiagnosticsTests(unittest.TestCase):
    def test_resolver_configuration_returns_nameservers_and_options_only(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "resolv.conf"
            path.write_text(
                "# generated by Docker\n"
                "nameserver 127.0.0.11\n"
                "search private.example.local\n"
                "options ndots:0 timeout:2 attempts:2 rotate\n",
                encoding="utf-8",
            )
            result = resolver_configuration(path)

        self.assertEqual(result["nameservers"], ["127.0.0.11"])
        self.assertEqual(result["options"], ["ndots:0", "timeout:2", "attempts:2", "rotate"])
        self.assertNotIn("search", result)

    def test_resolve_host_deduplicates_addresses(self) -> None:
        records = [
            (socket.AF_INET, socket.SOCK_STREAM, 6, "", ("203.0.113.10", 443)),
            (socket.AF_INET, socket.SOCK_STREAM, 6, "", ("203.0.113.10", 443)),
            (socket.AF_INET6, socket.SOCK_STREAM, 6, "", ("2001:db8::10", 443, 0, 0)),
        ]
        with patch("app.network_diagnostics.socket.getaddrinfo", return_value=records):
            result = resolve_host("example.test")

        self.assertTrue(result["ok"])
        self.assertEqual(result["addresses"], ["203.0.113.10", "2001:db8::10"])

    def test_dns_failure_is_classified(self) -> None:
        error = socket.gaierror(-3, "Temporary failure in name resolution")
        with patch("app.network_diagnostics.socket.getaddrinfo", side_effect=error):
            result = resolve_host("anibt.net")

        self.assertFalse(result["ok"])
        self.assertEqual(result["error_type"], "dns")
        self.assertIn("Temporary failure", result["message"])

    def test_all_failed_targets_return_container_dns_guidance(self) -> None:
        targets = (
            NetworkTarget("Mikan", "https://mikanime.tv"),
            NetworkTarget("ANI.BT", "https://anibt.net"),
        )
        failed = {
            "host": "",
            "ok": False,
            "addresses": [],
            "error_type": "dns",
            "message": "dns failed",
        }
        with (
            patch("app.network_diagnostics.configured_network_targets", return_value=targets),
            patch("app.network_diagnostics.resolve_host", side_effect=lambda host: {**failed, "host": host}),
            patch("app.network_diagnostics.resolver_configuration", return_value={"nameservers": ["127.0.0.11"], "options": []}),
        ):
            result = diagnose_dns()

        self.assertFalse(result["ok"])
        self.assertIn("无法解析任何", result["summary"])
        self.assertEqual(len(result["checks"]), 2)
        self.assertTrue(any("重新创建容器" in item for item in result["remediation"]))


if __name__ == "__main__":
    unittest.main()
